# Sample Makefile for a Rust project

SHELL := /bin/fish
.PHONY: help

help:
	@grep -E '^[a-zA-Z_-]+:' Makefile | 

clean: ## Clean the project using cargo
	cargo clean

build: ## Build the project using cargo
	cargo build --release

